### ISSUE TITLE
urandom is never closed

### ISSUE THREAD

**Issue by marco-palumbi** [dsprenkels/randombytes#33]
Hi Daan, I found a little issue here:
https://github.com/dsprenkels/randombytes/blob/a29d979988c53b0a5e3db15ea3c14f247ffdc424/randombytes.c#L221

/dev/urandom is opened at each call of the **randombytes_linux_randombytes_urandom()** but never closed.
I would suggest ether:
- close at the exit of the function
- use for **fd** a static variable initialized to -1 test it and if equal to -1 open the device and assign the descriptor to **fd**

the last could save some time if the function is called repeatedly

**Comment by thomwiggers** [comment]
> * use for **fd** a static variable initialized to -1 test it and if equal to -1 open the device and assign the descriptor to **fd**
> 
> the last could save some time if the function is called repeatedly

I don't think that's thread-safe; and using `thread_local` probably imposes requirements that you don't want to include everywhere...

**Comment by marco-palumbi** [comment]
probably you are right @thomwiggers.
for a thread-safe safe implementation remain the option of closing the descriptor at each call or use a sort of init_random() to be called at the very beginning from the first thread..

**Comment by thomwiggers** [comment]
I highly doubt that's worth the complexity for what is essentially a fallback used only if more modern methods (`getentropy`) aren't available.

**Comment by marco-palumbi** [comment]
well.. if the code is there it can be used... and if you use it for any reason if you call the function for a while, you will get an error because you reach the maximum for the open file descriptors.
I got the bug because I used this code and after a while I start getting the error "Too many open files"

please note that each time you call the randombytes() function a new file descriptor is opened

**Comment by thomwiggers** [comment]
To clarify: closing the file descriptor is worth it; thread-local storage or init functions aren't.

**Comment by marco-palumbi** [comment]
We are on the same page then.. 
I had interpreted your previous comment in a more general way, sorry for that

**Comment by dsprenkels** [comment]
Lol. @marrit-git just pointed out to me that this bug has actually been documented for more than 4 years. :')

https://github.com/dsprenkels/randombytes/commit/e9cb6e9c53cc289f0ac327597c9a79f857fc941f#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R17-R19
