### ISSUE TITLE
CryptGenRandom expects DWORD

### ISSUE THREAD

**Issue by dsprenkels** [dsprenkels/randombytes#38]
Upstream copy of https://github.com/PQClean/PQClean/pull/438

**Comment by dsprenkels** [comment]
This is probably as easy as directly applying the https://github.com/PQClean/PQClean/commit/45c8d1e073367cb4b991a1d690dbdcd8bbf4ed46.diff

**Comment by thomwiggers** [comment]
Maybe you want to actually do some error handling; the cast I added might truncate.

**Comment by thomwiggers** [comment]
Fixed by #40

**Comment by dsprenkels** [comment]
Fixed by #40
